### ISSUE TITLE
Error with the newest Version

### ISSUE THREAD

**Issue by editon96** [PikaMug/Unite#3]
Hey I have Purpur 1.19.3 Build 1916
I Install you Update and get that Error.

https://pastebin.com/BFqTK9Gi

Thanks for reading.
Have a great day!

**Comment by PikaMug** [comment]
Thanks for the report. Do you have any other party plugins installed besides mcMMO?

**Comment by editon96** [comment]
Yes I have Installed:
- mcmmo
- mmocore
- paf on velocity (party and friends)

Not sure
- maybe cmi has something like that too but I deactivate it
- clans
- guilds
- lands

I am not sure by all of them IF they have an Party Feture. But the most I can deactivate I do because I want only Party and Friends Partys.

**Comment by PikaMug** [comment]
Thanks. Just to be clear—you have [this version of Party And Friends](https://www.spigotmc.org/resources/party-and-friends-extended-edition-for-bungeecord-velocity-supports-1-7-1-19.10123/) installed on a Velocity server, and Unite installed on a Spigot/Paper server?

**Comment by editon96** [comment]
Yes I have Paf Extendet on Velocity and Purpur Installed and I now that Unite only support the Bukkit version.

**Comment by PikaMug** [comment]
Alright. Please give this version a try when you get a chance (no need to make an account):
https://www.dropbox.com/s/yw2qcfqds9b1wp2/Unite-1.1.7-SNAPSHOT.jar?dl=0

**Comment by editon96** [comment]
I try it when I have Time for it. I think in the next Weekend I get the Time...
Thanks.

**Comment by PikaMug** [comment]
@editon96 Feel free to request re-open if you encounter an issue.
