### ISSUE TITLE
Error spamming console

### ISSUE THREAD

**Issue by HorusApl** [PikaMug/Unite#5]
On any player interact: https://mclo.gs/B5jgzfM & https://mclo.gs/YpRukGQ

mcMMO version 2.2.004
mcMMO Overhaul Quests Module 2.2
Unite version 1.1.7
Quests version 5.0.1-b454
Server version: git-Purpur-2151 (MC: 1.20.4)*

Directed here from https://github.com/Browsit/mcMMOQuestsModule/issues/5 after testing with a blank quests config.

**Comment by PikaMug** [comment]
@HorusApl Would you mind testing this development build of Unite? I updated the mcMMO integration, but they're using Java 16 now. https://ci.codemc.io/job/PikaMug/job/Unite/2/me.pikamug.unite$Unite/

**Comment by HorusApl** [comment]
No longer seeing the error message. Did a basic quest of mining diamonds to reward mcMMO Mining levels which worked fine and awarded the correct amount of levels.
