### ISSUE TITLE
McMMO Skill Level rewards are not granted

### ISSUE THREAD

**Issue by HorusApl** [PikaMug/Unite#6]
When doing a quest that has any skill reward of any type, the reward is not given if a details-override is set. Without it, it works fine. With it, it doesn't give anything.

Example Quest:
https://mclo.gs/GoXd2dw

**Comment by PikaMug** [comment]
Unite only handles party integration. Please report this on the Quests issue tracker if you're using Classic, or the module tracker if you're using Overhaul.
