### ISSUE TITLE
McMMO Skill Reward Allowing beyond max level

### ISSUE THREAD

**Issue by HorusApl** [PikaMug/Unite#7]
McMMO has a config option to cap the max level of X skill at a certain number. If a quest gives a skill reward, it will take them above what should be the max level. It shouldn't be possible and just removing the quests from being completeable by those with a max level would remove it from those who don't have it as well.

**Comment by PikaMug** [comment]
Unite only handles party integration. Please report this on the Quests issue tracker if you're using Classic, or the module tracker if you're using Overhaul.
